name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    env:
      NODE_ENV: production
      PORT: 3000
      RUN_DIR: C:\apps\gh-actions-demo

    steps:
      - name: Ensure runtime directory exists
        run: |
          if (!(Test-Path $env:RUN_DIR)) {
            New-Item -Path $env:RUN_DIR -ItemType Directory | Out-Null
          }
        shell: powershell

      - name: Download CI artifact
        uses: actions/download-artifact@v4
        with:
          name: app-${{ github.event.workflow_run.head_sha }}
          run-id: ${{ github.event.workflow_run.id }}
          path: ${{ env.RUN_DIR }}

      - name: Unzip artifact
        run: |
          Expand-Archive -Path "$env:RUN_DIR\app.zip" -DestinationPath "$env:RUN_DIR" -Force
        shell: powershell

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install production dependencies
        run: |
          cd $env:RUN_DIR
          npm ci --omit=dev
        shell: powershell

      - name: Start application
        run: |
          cd $env:RUN_DIR
          Stop-Process -Name "node" -ErrorAction SilentlyContinue
          Start-Process "node" "dist\index.js"
        shell: powershell
